//! Live-host doctor coverage for the installed Rust toolchain.
//!
//! Keep this as a single-test integration target. The product intentionally gives toolchain
//! probes a bounded execution budget, so scheduling the test beside the broad process-heavy CLI
//! contract matrix makes host contention part of the assertion. A future test runner that runs
//! integration targets concurrently must preserve this isolation explicitly.

use serde_json::Value;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::{Command, Output};
use tempfile::TempDir;

#[derive(Debug)]
struct DoctorWorkspace {
    root: TempDir,
    worktree: PathBuf,
    global_git_config: PathBuf,
    xdg_config_home: PathBuf,
}

impl DoctorWorkspace {
    fn new() -> Result<Self, Box<dyn std::error::Error>> {
        let root = tempfile::tempdir()?;
        let worktree = root.path().join("worktree");
        let support = root.path().join("support");
        let xdg_config_home = support.join("xdg");
        fs::create_dir(&worktree)?;
        fs::create_dir(&support)?;
        fs::create_dir(&xdg_config_home)?;
        let global_git_config = support.join("global.gitconfig");
        fs::write(&global_git_config, b"")?;

        let fixture = Self {
            root,
            worktree,
            global_git_config,
            xdg_config_home,
        };
        fixture.run_git(&["init", "--quiet"])?;
        fs::create_dir(fixture.worktree.join("src"))?;
        fs::write(
            fixture.worktree.join("Cargo.toml"),
            b"[package]\nname = \"doctor-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )?;
        fs::write(
            fixture.worktree.join("Cargo.lock"),
            b"# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"doctor-fixture\"\nversion = \"0.1.0\"\n",
        )?;
        fs::write(
            fixture.worktree.join("src/lib.rs"),
            b"pub fn fixture() {}\n",
        )?;
        fixture.run_git(&["add", "--", "Cargo.toml", "Cargo.lock", "src/lib.rs"])?;
        Ok(fixture)
    }

    fn run_forge(&self, arguments: &[&str]) -> io::Result<Output> {
        let mut command = Command::new(env!("CARGO_BIN_EXE_forge"));
        command.current_dir(&self.worktree).args(arguments);
        self.configure_git_environment(&mut command);
        command.output()
    }

    fn run_git(&self, arguments: &[&str]) -> io::Result<()> {
        let output = self.git_output(arguments)?;
        if output.status.success() {
            return Ok(());
        }
        Err(io::Error::other(format!(
            "git {arguments:?} failed with status {:?}: {}",
            output.status.code(),
            String::from_utf8_lossy(&output.stderr).trim_end()
        )))
    }

    fn snapshot(&self) -> io::Result<GitSnapshot> {
        Ok(GitSnapshot {
            status: self.successful_git_stdout(&[
                "status",
                "--porcelain=v2",
                "-z",
                "--branch",
                "--untracked-files=all",
            ])?,
            tracked_paths: self.successful_git_stdout(&["ls-files", "--cached", "-z", "--"])?,
            untracked_paths: self.successful_git_stdout(&[
                "ls-files",
                "--others",
                "--exclude-standard",
                "-z",
                "--",
            ])?,
            index_diff: self.successful_git_stdout(&[
                "diff",
                "--cached",
                "--no-ext-diff",
                "--binary",
                "--",
            ])?,
            worktree_diff: self.successful_git_stdout(&[
                "diff",
                "--no-ext-diff",
                "--binary",
                "--",
            ])?,
        })
    }

    fn assert_no_forge_artifacts(&self) {
        assert!(!self.worktree.join("forge.toml").exists());
        assert!(!self.worktree.join(".forge").exists());
    }

    fn git_output(&self, arguments: &[&str]) -> io::Result<Output> {
        let mut command = Command::new("git");
        command
            .current_dir(&self.worktree)
            .arg("--no-pager")
            .arg("--no-optional-locks")
            .arg("-c")
            .arg("core.fsmonitor=false")
            .arg("-c")
            .arg("core.autocrlf=false")
            .args(arguments);
        self.configure_git_environment(&mut command);
        command.output()
    }

    fn successful_git_stdout(&self, arguments: &[&str]) -> io::Result<Vec<u8>> {
        let output = self.git_output(arguments)?;
        if output.status.success() {
            return Ok(output.stdout);
        }
        Err(io::Error::other(format!(
            "git {arguments:?} failed with status {:?}: {}",
            output.status.code(),
            String::from_utf8_lossy(&output.stderr).trim_end()
        )))
    }

    fn configure_git_environment(&self, command: &mut Command) {
        for name in [
            "GIT_CONFIG",
            "GIT_CONFIG_COUNT",
            "GIT_CONFIG_PARAMETERS",
            "GIT_CONFIG_SYSTEM",
            "GIT_CEILING_DIRECTORIES",
            "GIT_DIR",
            "GIT_WORK_TREE",
            "GIT_COMMON_DIR",
            "GIT_INDEX_FILE",
            "GIT_OBJECT_DIRECTORY",
            "GIT_ALTERNATE_OBJECT_DIRECTORIES",
            "GIT_NAMESPACE",
            "GIT_EXEC_PATH",
            "GIT_EXTERNAL_DIFF",
        ] {
            command.env_remove(name);
        }
        command
            .env("GIT_CONFIG_NOSYSTEM", "1")
            .env("GIT_CONFIG_GLOBAL", &self.global_git_config)
            .env("GIT_CEILING_DIRECTORIES", self.root.path())
            .env("GIT_ATTR_NOSYSTEM", "1")
            .env("GIT_TERMINAL_PROMPT", "0")
            .env("GIT_OPTIONAL_LOCKS", "0")
            .env("GIT_PAGER", "cat")
            .env("XDG_CONFIG_HOME", &self.xdg_config_home)
            .env("LC_ALL", "C");
    }
}

#[derive(Debug, PartialEq, Eq)]
struct GitSnapshot {
    status: Vec<u8>,
    tracked_paths: Vec<u8>,
    untracked_paths: Vec<u8>,
    index_diff: Vec<u8>,
    worktree_diff: Vec<u8>,
}

#[test]
fn doctor_reports_only_actually_probed_rust_command_dependencies()
-> Result<(), Box<dyn std::error::Error>> {
    let fixture = DoctorWorkspace::new()?;
    let before = fixture.snapshot()?;

    let output = fixture.run_forge(&["doctor", "--json"])?;
    let parsed = serde_json::from_slice::<Value>(&output.stdout);

    assert_eq!(
        output.status.code(),
        Some(1),
        "parsed stdout: {parsed:#?}\nraw stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    assert!(
        output.stderr.is_empty(),
        "unexpected stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let document = parsed?;
    let checks = document["data"]["checks"]
        .as_array()
        .ok_or_else(|| io::Error::other("doctor checks are missing"))?;
    let toolchain = checks
        .iter()
        .find(|check| check["id"] == "toolchain.required")
        .ok_or_else(|| io::Error::other("toolchain doctor check is missing"))?;
    assert_eq!(
        toolchain["status"], "pass",
        "unexpected doctor output: {document:#}"
    );
    let versions = document["data"]["tool_versions"]
        .as_object()
        .ok_or_else(|| io::Error::other("doctor tool versions are missing"))?;
    for tool in ["cargo", "rustc", "rustfmt"] {
        assert!(
            versions
                .get(tool)
                .and_then(Value::as_str)
                .is_some_and(|version| !version.is_empty()),
            "missing validated {tool} version: {versions:?}"
        );
    }
    assert_eq!(versions.len(), 3);
    assert_eq!(fixture.snapshot()?, before);
    fixture.assert_no_forge_artifacts();
    Ok(())
}
