//! Side-effect-bounded orchestration for `forge init`.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt::{self, Write as _};
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

use forge_core::branding::CLI_NAME;
use forge_core::{AppError, ExitCode, WorkState};
use forge_detect::model::ModelDetectionCompletion;
use forge_render::managed_block::ManagedBlockError;
use forge_render::{
    AdapterTarget, ApplyError, ApplyErrorKind, ApplyReport, ChangePlan, FileEditKind,
    InitPlanOptions, ManagedBlockKind, PlanError, SkippedReason, apply_change_plan, plan_init,
};
use forge_runtime::fs::NativeFileSystem;
use forge_runtime::hash::Blake3Hasher;
use forge_schema::{Diagnostic, InitPlanData, Severity};

use crate::args::{AdapterChoice, CiChoice, Cli, InitArgs, RunnerChoice};
use crate::explain;
use crate::init_wire::{InitPlanWireError, project_init_plan_to_wire};

/// A completed init request. The plan remains the pre-apply artifact that the user reviewed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct InitOutcome {
    pub(crate) plan: ChangePlan,
    pub(crate) wire: InitPlanData,
    pub(crate) applied: bool,
    pub(crate) apply_report: Option<ApplyReport>,
    pub(crate) completion: ModelDetectionCompletion,
    pub(crate) postcheck_completion: Option<ModelDetectionCompletion>,
}

/// An init failure coupled to any writes that completed before the failure was observed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct InitFailure {
    app_error: AppError,
    apply_report: Option<ApplyReport>,
}

impl InitFailure {
    #[must_use]
    pub(crate) fn into_parts(self) -> (AppError, Option<ApplyReport>) {
        (self.app_error, self.apply_report)
    }

    fn plain(app_error: AppError) -> Self {
        Self {
            app_error,
            apply_report: None,
        }
    }

    fn after_apply(app_error: AppError, apply_report: ApplyReport) -> Self {
        let diagnostic = app_error.diagnostic();
        let app_error = AppError::new(
            app_error.exit_code(),
            Diagnostic::new(
                diagnostic.code.clone(),
                diagnostic.severity,
                diagnostic.what.clone(),
                diagnostic.location.clone(),
                format!(
                    "{}; {}",
                    diagnostic.why,
                    apply_report_summary(&apply_report)
                ),
                format!(
                    "{}; treat the reported write progress as authoritative when reviewing or rolling back",
                    diagnostic.next
                ),
            ),
        );
        Self {
            app_error,
            apply_report: Some(apply_report),
        }
    }
}

impl fmt::Display for InitFailure {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.app_error.fmt(formatter)
    }
}

impl Error for InitFailure {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(&self.app_error)
    }
}

impl From<AppError> for InitFailure {
    fn from(error: AppError) -> Self {
        Self::plain(error)
    }
}

/// Detects and plans init, and writes only when the caller explicitly selected `--apply`.
pub(crate) fn execute(
    cli: &Cli,
    args: &InitArgs,
    cancellation: Arc<AtomicBool>,
) -> Result<InitOutcome, InitFailure> {
    validate_request(args)?;
    let options = init_plan_options(args)?;
    let detected = explain::detect(cli, Arc::clone(&cancellation))?;

    if args.apply {
        ensure_detection_can_apply(detected.completion)?;
        ensure_work_state_can_apply(detected.model.repository.work_state, args.allow_dirty)?;
    }

    let filesystem = NativeFileSystem;
    let hasher = Blake3Hasher;
    let repository_root = detected.model.repository.root.clone();
    let plan =
        plan_init(&detected.model, &filesystem, &hasher, &options).map_err(map_plan_error)?;
    let wire =
        project_init_plan_to_wire(&plan, &repository_root).map_err(map_wire_projection_error)?;

    if !args.apply {
        return Ok(InitOutcome {
            plan,
            wire,
            applied: false,
            apply_report: None,
            completion: detected.completion,
            postcheck_completion: None,
        });
    }

    // Re-detect every input that authorized the reviewed plan immediately before writing. Target
    // preimages protect managed files; this second model also closes races in manifests, runners,
    // work state, and other inputs that can change the generated bytes without touching a target.
    let preapply = explain::detect(cli, Arc::clone(&cancellation))?;
    ensure_detection_can_apply(preapply.completion)?;
    ensure_work_state_can_apply(preapply.model.repository.work_state, args.allow_dirty)?;
    if preapply.model.repository.id != plan.repository
        || preapply.model.repository.root != repository_root
    {
        return Err(InitFailure::plain(AppError::new(
            ExitCode::Temporary,
            Diagnostic::new(
                "FGE2213",
                Severity::Error,
                "repository selection changed before init apply",
                "init pre-apply check",
                "the repository identity or root no longer matches the reviewed plan",
                "review a fresh dry-run in the intended repository before applying",
            ),
        )));
    }
    let current_plan = plan_init(&preapply.model, &filesystem, &hasher, &options)
        .map_err(|error| InitFailure::plain(map_plan_error_app(error, "init pre-apply check")))?;
    if current_plan != plan {
        return Err(InitFailure::plain(AppError::new(
            ExitCode::Temporary,
            Diagnostic::new(
                "FGE2214",
                Severity::Error,
                "repository inputs changed after the init plan was produced",
                "init pre-apply check",
                "a fresh plan is not byte-for-byte equal to the reviewed plan; no files were written",
                "rerun the dry-run, review the new plan, then request `--apply` again",
            ),
        )));
    }

    let report = apply_change_plan(&repository_root, &plan, &filesystem, &hasher)
        .map_err(map_apply_error)?;
    let postcheck = explain::detect(cli, cancellation)
        .map_err(|error| InitFailure::after_apply(error, report.clone()))?;
    ensure_postcheck_completed(postcheck.completion, &report)?;
    if postcheck.model.repository.id != plan.repository
        || postcheck.model.repository.root != repository_root
    {
        return Err(InitFailure::after_apply(
            AppError::internal(
                "FGE0210",
                "post-apply detection resolved a different repository",
                "init post-check",
                format!(
                    "the reviewed repository was `{}` at `{}`, but the post-check resolved `{}` at `{}`",
                    plan.repository.as_str(),
                    display_repository_path(&repository_root),
                    postcheck.model.repository.id.as_str(),
                    display_repository_path(&postcheck.model.repository.root),
                ),
                "inspect the written paths and repository selection before retrying; use the reported rollback guidance if recovery is required",
            ),
            report,
        ));
    }
    let post_plan =
        plan_init(&postcheck.model, &filesystem, &hasher, &options).map_err(|error| {
            InitFailure::after_apply(map_plan_error_app(error, "init post-check"), report.clone())
        })?;
    if !post_plan.edits.is_empty() {
        let remaining = post_plan
            .edits
            .iter()
            .map(|edit| display_repository_path(edit.path.as_path()))
            .collect::<Vec<_>>()
            .join(", ");
        return Err(InitFailure::after_apply(
            AppError::internal(
                "FGE0211",
                "applied init output did not converge to a no-op",
                "init post-check",
                format!("a fresh detection still planned edits for [{remaining}]",),
                "inspect the written files and rerun a dry-run; roll back the reported paths if the generated state is not acceptable",
            ),
            report,
        ));
    }

    Ok(InitOutcome {
        plan,
        wire,
        applied: true,
        apply_report: Some(report),
        completion: detected.completion,
        postcheck_completion: Some(postcheck.completion),
    })
}

fn validate_request(args: &InitArgs) -> Result<(), InitFailure> {
    if args.apply && args.dry_run {
        return Err(InitFailure::plain(AppError::usage(
            "FGE1201",
            "init cannot select both preview and apply modes",
            "--dry-run / --apply",
            "the two modes have different side-effect contracts",
            "select at most one mode; omitting both is a dry-run",
        )));
    }
    if let Some(runner) = args.with_runner {
        return Err(InitFailure::plain(unavailable_runner_error(runner)));
    }
    if let Some(provider) = args.with_ci {
        return Err(InitFailure::plain(unavailable_ci_error(provider)));
    }
    Ok(())
}

fn unavailable_runner_error(runner: RunnerChoice) -> AppError {
    AppError::environment_unmet(
        "FGE2201",
        format!(
            "explicit `{}` runner generation is not available in this build",
            runner_name(runner)
        ),
        "--with-runner",
        "Forge cannot yet render and verify this opt-in asset, so it will not silently ignore the request",
        format!(
            "remove `--with-runner {}` and use detected native commands, or use a Forge build that implements explicit runner generation",
            runner_name(runner)
        ),
    )
}

fn unavailable_ci_error(provider: CiChoice) -> AppError {
    AppError::environment_unmet(
        "FGE2202",
        format!(
            "explicit `{}` CI draft generation is not available in this build",
            ci_name(provider)
        ),
        "--with-ci",
        "Forge cannot yet render and verify this opt-in asset, so it will not silently ignore the request",
        format!(
            "remove `--with-ci {}` or use a Forge build that implements explicit CI draft generation",
            ci_name(provider)
        ),
    )
}

const fn runner_name(runner: RunnerChoice) -> &'static str {
    match runner {
        RunnerChoice::Make => "make",
        RunnerChoice::Just => "just",
        RunnerChoice::Task => "task",
    }
}

const fn ci_name(provider: CiChoice) -> &'static str {
    match provider {
        CiChoice::Github => "github",
    }
}

fn init_plan_options(args: &InitArgs) -> Result<InitPlanOptions, InitFailure> {
    let adapters = args
        .adapter
        .iter()
        .copied()
        .map(|adapter| match adapter {
            AdapterChoice::Claude => AdapterTarget::Claude,
            AdapterChoice::Cursor => AdapterTarget::Cursor,
        })
        .collect();
    let force_blocks = parse_force_blocks(&args.force_block)?;
    Ok(InitPlanOptions {
        adapters,
        force_blocks,
    })
}

fn parse_force_blocks(values: &[String]) -> Result<Vec<ManagedBlockKind>, InitFailure> {
    let mut blocks = Vec::with_capacity(values.len());
    let mut unique = BTreeSet::new();
    for value in values {
        let block = match value.as_str() {
            "project-index" => ManagedBlockKind::ProjectIndex,
            "claude-pointer" => ManagedBlockKind::ClaudePointer,
            _ => {
                return Err(InitFailure::plain(AppError::usage(
                    "FGE1202",
                    "unknown managed block selected for replacement",
                    "--force-block",
                    format!("`{value}` is not one of the managed blocks owned by this Forge build"),
                    "use `--force-block project-index` or `--force-block claude-pointer`",
                )));
            }
        };
        if !unique.insert(block) {
            return Err(InitFailure::plain(AppError::usage(
                "FGE1203",
                "the same managed block was selected more than once",
                "--force-block",
                format!("`{value}` occurs more than once"),
                "remove the duplicate option",
            )));
        }
        blocks.push(block);
    }
    Ok(blocks)
}

fn ensure_detection_can_apply(completion: ModelDetectionCompletion) -> Result<(), InitFailure> {
    let (exit_code, code, what, why, next) = match completion {
        ModelDetectionCompletion::Complete | ModelDetectionCompletion::Partial => return Ok(()),
        ModelDetectionCompletion::TimedOut => (
            ExitCode::Timeout,
            "FGE2203",
            "init detection timed out before apply",
            "the partial model is reviewable but is not a safe write authority",
            "increase `--timeout`, address the slow metadata source, then rerun the dry-run before applying",
        ),
        ModelDetectionCompletion::Interrupted => (
            ExitCode::Interrupted,
            "FGE2204",
            "init detection was interrupted before apply",
            "the partial model is reviewable but is not a safe write authority",
            "rerun the dry-run when ready, review the plan, then request `--apply` again",
        ),
    };
    Err(InitFailure::plain(AppError::new(
        exit_code,
        Diagnostic::new(code, Severity::Error, what, "init detection", why, next),
    )))
}

fn ensure_work_state_can_apply(state: WorkState, allow_dirty: bool) -> Result<(), InitFailure> {
    match state {
        WorkState::Clean => Ok(()),
        WorkState::Dirty | WorkState::Unborn if allow_dirty => Ok(()),
        WorkState::Dirty | WorkState::Unborn => {
            Err(InitFailure::plain(AppError::environment_unmet(
                "FGE2205",
                "init apply requires a clean worktree",
                "Git worktree",
                format!(
                    "the initial repository state is `{}` and `--allow-dirty` was not selected",
                    work_state_name(state)
                ),
                "commit, stash, or otherwise preserve existing work; alternatively rerun with `--allow-dirty` after reviewing the rollback limitations",
            )))
        }
        WorkState::Conflicted
        | WorkState::Merging
        | WorkState::Rebasing
        | WorkState::Corrupt
        | WorkState::Unknown => Err(InitFailure::plain(AppError::environment_unmet(
            "FGE2206",
            "init apply is unsafe in the current repository state",
            "Git worktree",
            format!(
                "the initial repository state is `{}`; `--allow-dirty` cannot override unresolved or untrusted repository state",
                work_state_name(state)
            ),
            "finish or abort the Git operation, resolve conflicts, or repair repository inspection before rerunning the dry-run",
        ))),
    }
}

fn ensure_postcheck_completed(
    completion: ModelDetectionCompletion,
    report: &ApplyReport,
) -> Result<(), InitFailure> {
    let (exit_code, code, what, why, next) = match completion {
        ModelDetectionCompletion::Complete | ModelDetectionCompletion::Partial => return Ok(()),
        ModelDetectionCompletion::TimedOut => (
            ExitCode::Timeout,
            "FGE2207",
            "init wrote its plan but the post-apply detection timed out",
            String::from("idempotence could not be verified"),
            "inspect the reported written paths, rerun a dry-run with a larger timeout, and use the rollback guidance if verification does not converge",
        ),
        ModelDetectionCompletion::Interrupted => (
            ExitCode::Interrupted,
            "FGE2208",
            "init wrote its plan but the post-apply detection was interrupted",
            String::from("idempotence could not be verified"),
            "inspect the reported written paths, rerun a dry-run when ready, and use the rollback guidance if verification does not converge",
        ),
    };
    Err(InitFailure::after_apply(
        AppError::new(
            exit_code,
            Diagnostic::new(code, Severity::Error, what, "init post-check", why, next),
        ),
        report.clone(),
    ))
}

const fn work_state_name(state: WorkState) -> &'static str {
    match state {
        WorkState::Clean => "clean",
        WorkState::Dirty => "dirty",
        WorkState::Conflicted => "conflicted",
        WorkState::Merging => "merging",
        WorkState::Rebasing => "rebasing",
        WorkState::Unborn => "unborn",
        WorkState::Corrupt => "corrupt",
        WorkState::Unknown => "unknown",
    }
}

fn map_plan_error(error: PlanError) -> InitFailure {
    InitFailure::plain(map_plan_error_app(error, "init plan"))
}

fn map_plan_error_app(error: PlanError, location: &str) -> AppError {
    let detail = error.to_string();
    match error {
        PlanError::NoProjectFacts => AppError::environment_unmet(
            "FGE2209",
            "no project commands or units could be established for init",
            location,
            "the repository does not contain enough trusted facts to generate a useful host index",
            "establish the project with its ecosystem's normal tools or add an explicit Forge command configuration, then rerun the dry-run",
        ),
        PlanError::DuplicateAdapterRequest(adapter) => AppError::usage(
            "FGE1204",
            "the same host adapter was requested more than once",
            "--adapter",
            format!("adapter `{}` occurs more than once", adapter_name(adapter)),
            "remove the duplicate adapter option",
        ),
        PlanError::DuplicateForceBlock(block) => AppError::usage(
            "FGE1203",
            "the same managed block was selected more than once",
            "--force-block",
            format!("`{}` occurs more than once", block.id()),
            "remove the duplicate option",
        ),
        PlanError::Read { path, source } => AppError::environment_unmet(
            "FGE2210",
            "a planned adapter target could not be read safely",
            display_repository_path(path.as_path()),
            sanitize_text(&source.to_string()),
            "fix the path, permissions, or symbolic-link boundary, then rerun the dry-run",
        ),
        PlanError::ManagedBlock { path, source } => {
            let next = managed_block_recovery(&source);
            AppError::data(
                "FGE1205",
                "managed adapter content cannot be updated safely",
                display_repository_path(path.as_path()),
                sanitize_text(&source.to_string()),
                next,
            )
        }
        PlanError::InvalidTarget(_)
        | PlanError::DuplicateTarget(_)
        | PlanError::InvalidModel(_)
        | PlanError::GeneratedBlockLimit { .. } => AppError::internal(
            "FGE0212",
            "init planning violated a rendering invariant",
            location,
            sanitize_text(&detail),
            format!(
                "report this as a {CLI_NAME} implementation defect with the repository shape and command"
            ),
        ),
    }
}

fn managed_block_recovery(error: &ManagedBlockError) -> String {
    match error {
        ManagedBlockError::UserEdited { id } => format!(
            "move durable requirements outside the managed block, rerun the dry-run, or explicitly select `--force-block {id}` after reviewing the replacement"
        ),
        ManagedBlockError::UnsupportedSchema { .. } => {
            String::from("upgrade Forge before changing a block written by a newer marker schema")
        }
        ManagedBlockError::InvalidUtf8
        | ManagedBlockError::InvalidBlockId(_)
        | ManagedBlockError::MalformedMarker { .. }
        | ManagedBlockError::NestedBlock { .. }
        | ManagedBlockError::OrphanEnd { .. }
        | ManagedBlockError::MismatchedEnd { .. }
        | ManagedBlockError::UnterminatedBlock { .. }
        | ManagedBlockError::DuplicateBlock { .. } => String::from(
            "repair the malformed or duplicate managed markers without changing unrelated file bytes, then rerun the dry-run",
        ),
    }
}

fn map_wire_projection_error(error: InitPlanWireError) -> InitFailure {
    InitFailure::plain(AppError::internal(
        "FGE0213",
        "the init plan cannot be represented by the public contract",
        "forge.init-plan/v1",
        sanitize_text(&error.to_string()),
        format!(
            "report this as a {CLI_NAME} implementation defect with the dry-run command and repository shape"
        ),
    ))
}

fn map_apply_error(error: ApplyError) -> InitFailure {
    let report = error.report().clone();
    let location = error.path().map_or_else(
        || String::from("init apply"),
        |path| display_repository_path(path.as_path()),
    );
    let detail = sanitize_text(&error.to_string());
    let app_error = match error.kind() {
        ApplyErrorKind::PreimagePresenceMismatch
        | ApplyErrorKind::PreimageDigestMismatch
        | ApplyErrorKind::PrewriteDrift => AppError::new(
            ExitCode::Temporary,
            Diagnostic::new(
                "FGE2211",
                Severity::Error,
                "the repository changed after the init plan was produced",
                location,
                detail,
                "review a fresh dry-run and apply that new plan; inspect any reported written paths before retrying",
            ),
        ),
        ApplyErrorKind::ManagedBlockConflict => AppError::data(
            "FGE1206",
            "managed adapter content conflicted during apply preflight",
            location,
            detail,
            "review a fresh dry-run and resolve the managed block conflict; force only the named block when replacement is intentional",
        ),
        ApplyErrorKind::ReadPreimage
        | ApplyErrorKind::ReadBeforeWrite
        | ApplyErrorKind::Write
        | ApplyErrorKind::ReadAfterWrite
        | ApplyErrorKind::PostwriteMissing
        | ApplyErrorKind::PostwriteMismatch => AppError::environment_unmet(
            "FGE2212",
            "init could not complete or verify its confined writes",
            location,
            detail,
            "inspect the reported written and unwritten paths, restore the listed preimages with Git when needed, then rerun a dry-run",
        ),
        ApplyErrorKind::UnsupportedPlanSchema
        | ApplyErrorKind::DuplicateTarget
        | ApplyErrorKind::InvalidEdit
        | ApplyErrorKind::UnexpectedMergeAction
        | ApplyErrorKind::PostimageDigestMismatch => AppError::internal(
            "FGE0214",
            "the reviewed init plan violated an apply invariant",
            location,
            detail,
            format!(
                "inspect any reported writes, then report this as a {CLI_NAME} implementation defect"
            ),
        ),
    };
    InitFailure::after_apply(app_error, report)
}

fn apply_report_summary(report: &ApplyReport) -> String {
    let written = report
        .written
        .iter()
        .map(|file| {
            format!(
                "{}(kind={},preimage={},postimage={},verified={})",
                display_repository_path(file.path.as_path()),
                edit_kind_name(file.kind),
                file.preimage
                    .as_ref()
                    .map_or("none", |digest| digest.as_str()),
                file.postimage.as_str(),
                file.verified,
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let unwritten = report
        .unwritten
        .iter()
        .map(|path| display_repository_path(path.as_path()))
        .collect::<Vec<_>>()
        .join(",");
    format!("apply report: written=[{written}], unwritten=[{unwritten}]")
}

const fn edit_kind_name(kind: FileEditKind) -> &'static str {
    match kind {
        FileEditKind::Create => "create",
        FileEditKind::ReplaceManagedBlock => "replace-managed-block",
    }
}

const fn adapter_name(adapter: AdapterTarget) -> &'static str {
    match adapter {
        AdapterTarget::Claude => "claude",
        AdapterTarget::Cursor => "cursor",
        AdapterTarget::Codex => "codex",
    }
}

const fn completion_name(completion: ModelDetectionCompletion) -> &'static str {
    match completion {
        ModelDetectionCompletion::Complete => "complete",
        ModelDetectionCompletion::Partial => "partial",
        ModelDetectionCompletion::TimedOut => "timed-out",
        ModelDetectionCompletion::Interrupted => "interrupted",
    }
}

const fn skipped_reason_name(reason: &SkippedReason) -> &'static str {
    match reason {
        SkippedReason::AlreadySatisfied => "already-satisfied",
        SkippedReason::EquivalentUnmanaged => "equivalent-unmanaged",
        SkippedReason::ReusesAgents(AdapterTarget::Claude) => "reuses-agents:claude",
        SkippedReason::ReusesAgents(AdapterTarget::Cursor) => "reuses-agents:cursor",
        SkippedReason::ReusesAgents(AdapterTarget::Codex) => "reuses-agents:codex",
    }
}

/// Renders the exact plan artifact without rescanning the repository or performing writes.
pub(crate) fn render_human(outcome: &InitOutcome) -> String {
    let mut output = String::new();
    let mode = if outcome.applied {
        "applied"
    } else {
        "dry-run"
    };
    let _ = writeln!(output, "repository: {}", outcome.plan.repository.as_str());
    let _ = writeln!(output, "mode: {mode}");
    let _ = writeln!(output, "detection: {}", completion_name(outcome.completion));
    if let Some(completion) = outcome.postcheck_completion {
        let _ = writeln!(output, "post-check: {}", completion_name(completion));
    }
    let _ = writeln!(output, "planned edits: {}", outcome.plan.edits.len());
    for edit in &outcome.plan.edits {
        let _ = writeln!(
            output,
            "  - {}: {} (block {}, preimage {}, postimage {})",
            edit_kind_name(edit.kind),
            display_repository_path(edit.path.as_path()),
            edit.desired.kind.id(),
            edit.expected_preimage
                .as_ref()
                .map_or("none", |digest| digest.as_str()),
            edit.expected_postimage.as_str(),
        );
        let _ = writeln!(
            output,
            "    UTF-8 postimage preview ({} bytes; control characters escaped):",
            edit.preview_postimage.len()
        );
        render_postimage(&mut output, &edit.preview_postimage);
    }
    let _ = writeln!(output, "assumptions: {}", outcome.plan.assumptions.len());
    for assumption in &outcome.plan.assumptions {
        let _ = writeln!(output, "  - {}", sanitize_text(&assumption.statement));
    }
    let _ = writeln!(output, "skipped: {}", outcome.plan.skipped.len());
    for skipped in &outcome.plan.skipped {
        let _ = writeln!(
            output,
            "  - {} ({})",
            display_repository_path(skipped.path.as_path()),
            skipped_reason_name(&skipped.reason),
        );
    }
    if let Some(report) = &outcome.apply_report {
        let _ = writeln!(output, "{}", apply_report_summary(report));
    }
    output.push_str("rollback:\n");
    for path in &outcome.plan.rollback.restore_modified {
        let _ = writeln!(
            output,
            "  restore modified: {}",
            display_repository_path(path.as_path())
        );
    }
    for path in &outcome.plan.rollback.remove_created {
        let _ = writeln!(
            output,
            "  remove created: {}",
            display_repository_path(path.as_path())
        );
    }
    let _ = writeln!(output, "  {}", outcome.wire.rollback.guidance);
    output
}

fn render_postimage(output: &mut String, bytes: &[u8]) {
    match std::str::from_utf8(bytes) {
        Ok(text) => {
            for segment in text.split_inclusive('\n') {
                let _ = writeln!(output, "      | {}", sanitize_text(segment));
            }
            if text.is_empty() {
                output.push_str("      | <empty>\n");
            }
        }
        Err(_) => {
            let _ = writeln!(output, "      <non-UTF-8 postimage: {} bytes>", bytes.len());
        }
    }
}

fn display_repository_path(path: &Path) -> String {
    sanitize_text(&path.as_os_str().to_string_lossy())
}

fn sanitize_text(value: &str) -> String {
    let mut sanitized = String::with_capacity(value.len());
    for character in value.chars() {
        if character.is_control() {
            let _ = write!(sanitized, "\\u{{{:x}}}", u32::from(character));
        } else {
            sanitized.push(character);
        }
    }
    sanitized
}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use forge_core::{ExitCode, WorkState};
    use forge_render::ManagedBlockKind;

    use super::{
        display_repository_path, ensure_work_state_can_apply, parse_force_blocks, render_postimage,
        sanitize_text, validate_request,
    };
    use crate::args::{CiChoice, InitArgs, RunnerChoice};

    #[test]
    fn force_blocks_accept_only_owned_ids_and_reject_duplicates() -> Result<(), Box<dyn Error>> {
        let values = vec![
            String::from("project-index"),
            String::from("claude-pointer"),
        ];
        let parsed = parse_force_blocks(&values)?;
        assert_eq!(
            parsed,
            [
                ManagedBlockKind::ProjectIndex,
                ManagedBlockKind::ClaudePointer
            ]
        );

        let unknown = parse_force_blocks(&[String::from("agents-index")]);
        match unknown {
            Ok(_) => return Err("unknown block id was accepted".into()),
            Err(error) => assert_eq!(error.into_parts().0.exit_code(), ExitCode::Usage),
        }
        let duplicate =
            parse_force_blocks(&[String::from("project-index"), String::from("project-index")]);
        match duplicate {
            Ok(_) => return Err("duplicate block id was accepted".into()),
            Err(error) => assert_eq!(error.into_parts().0.exit_code(), ExitCode::Usage),
        }
        Ok(())
    }

    #[test]
    fn apply_state_gate_allows_only_explicit_safe_cases() -> Result<(), Box<dyn Error>> {
        ensure_work_state_can_apply(WorkState::Clean, false)?;
        ensure_work_state_can_apply(WorkState::Dirty, true)?;
        ensure_work_state_can_apply(WorkState::Unborn, true)?;

        for state in [WorkState::Dirty, WorkState::Unborn] {
            match ensure_work_state_can_apply(state, false) {
                Ok(()) => return Err(format!("{state:?} was accepted without opt-in").into()),
                Err(error) => {
                    assert_eq!(error.into_parts().0.exit_code(), ExitCode::EnvironmentUnmet);
                }
            }
        }
        for state in [
            WorkState::Conflicted,
            WorkState::Merging,
            WorkState::Rebasing,
            WorkState::Corrupt,
            WorkState::Unknown,
        ] {
            match ensure_work_state_can_apply(state, true) {
                Ok(()) => return Err(format!("unsafe state {state:?} was accepted").into()),
                Err(error) => {
                    assert_eq!(error.into_parts().0.exit_code(), ExitCode::EnvironmentUnmet);
                }
            }
        }
        Ok(())
    }

    #[test]
    fn explicit_unavailable_generators_are_not_ignored() -> Result<(), Box<dyn Error>> {
        let mut args = init_args();
        args.with_runner = Some(RunnerChoice::Just);
        match validate_request(&args) {
            Ok(()) => return Err("unavailable runner generation was ignored".into()),
            Err(error) => {
                assert_eq!(error.into_parts().0.exit_code(), ExitCode::EnvironmentUnmet);
            }
        }

        args.with_runner = None;
        args.with_ci = Some(CiChoice::Github);
        match validate_request(&args) {
            Ok(()) => return Err("unavailable CI generation was ignored".into()),
            Err(error) => {
                assert_eq!(error.into_parts().0.exit_code(), ExitCode::EnvironmentUnmet);
            }
        }
        Ok(())
    }

    #[test]
    fn human_text_escapes_terminal_control_characters() {
        assert_eq!(sanitize_text("safe\u{1b}[31m"), "safe\\u{1b}[31m");
        assert_eq!(
            display_repository_path(std::path::Path::new("dir/\u{1b}[31m")),
            "dir/\\u{1b}[31m"
        );
    }

    #[test]
    fn postimage_preview_represents_trailing_newlines() {
        let mut output = String::new();
        render_postimage(&mut output, b"first\nsecond\n");

        assert_eq!(output, "      | first\\u{a}\n      | second\\u{a}\n");
    }

    fn init_args() -> InitArgs {
        InitArgs {
            dry_run: false,
            apply: false,
            allow_dirty: false,
            with_runner: None,
            with_ci: None,
            adapter: Vec::new(),
            force_block: Vec::new(),
        }
    }
}
